// This file initializes the dynamic library and connects it with the stub
// generated by flutter_rust_bridge_codegen.

import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'gened_api_1.web.dart';
import 'gened_api_2.web.dart';

// export 'bridge_definitions.dart';

const root = 'pkg/native';
final api_1 = Api1Impl.wasm(
  WasmModule.initialize(kind: const Modules.noModules(root: root)),
);

final api_2 = Api2Impl.wasm(
  WasmModule.initialize(kind: const Modules.noModules(root: root)),
);
